### ISSUE TITLE
XML formatting stripped from abstracts badly

### ISSUE THREAD

**Issue by gwern** [ropensci/pubchunks#11]
`pubchunks` at present appears to strip formatting from abstracts, such as emphasis/headers/subscripts, which are presented in the XML downloaded by `fulltext`. It would be better to either preserve the formatting or make the ASCII-fication better, at least, as it impedes downstream users.

I provide on my website extensive tooltip 'popups' which provide summaries/abstracts/excerpts of links. Readers find them far more useful than the usual barebone citations you see on my websites. Because they are so much work, I automate the creation of the popup for a given URL as much as possible; for PLOS URLs, I use `fulltext`+`pubchunks` to turn the URL/DOI into a title/author/date/DOI/abstract tuple. Unfortunately, I've noticed that the abstract is badly damaged by `pubchunks` (I think) processing. (A live example is in my [February 2020 newsletter](https://www.gwern.net/newsletter/2020/02#links), the link "The Evolution of Sex Ratio Distorter Suppression...", where all of the italics and the "Author Summary" header are messed up.)

Consider the example ["Unique Environmental Effects on Physical Activity Participation: A Twin Study", Duncan et al 2008](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0002019) (DOI: 10.1371/journal.pone.0002019). The HTML abstract is fine, and `fulltext` has no problem downloading the metadata to `/home/gwern/.cache/R/fulltext/10_1371_journal_pone_0002019.xml`; when I view that, the formatting of the abstract is correct (abstract internal divisions get `<title>` elements to put them into bold, statistical parameters like r<sub>MZ</sub> are correct, etc):

    <abstract><sec><title>Background</title><p>The health benefits of regular physical activity are well established. 
    However, the relative contribution of heritable and environmental factors to physical activity participation remains 
    controversial. Using a cut-point of 60 minutes of total activity per week, data from the GenomEUtwin project revealed 
    consistent genetic influence on physical activity participation in 37,051 twin pairs from seven countries. We hypothesized 
    that the heritability of physical activity participation would be attenuated using the CDC/ACSM recommended minimum   
    threshold of 150 minutes of moderate intensity activity per week.</p></sec><sec><title>Methods</title><p>Data were 
    obtained from 1,389 twin pairs from the community-based University of Washington Twin Registry. Twin similarity in 
    physical activity participation using both cut-points was analyzed using tetrachoric correlations and structural equation 
    modeling in all same-sex pairs.</p></sec><sec><title>Results</title><p>Correlations were higher in monozygotic 
    (r<sub>MZ</sub> = 0.43, 95% CI = 0.33–0.54) than dizygotic pairs (r<sub>DZ</sub> = 0.30, 95% CI = 0.12–0.47) ...

However, all of this is completely mangled after going through the `fulltext`+`pubchunks` pipeline:

~~~{.R}
R> library(fulltext)
R> fulltext <- ft_get("10.1371/journal.pone.0002019", from="plos")
# path exists: /home/gwern/.cache/R/fulltext/10_1371_journal_pone_0002019.xml
R> fulltext
# <fulltext text>
# [Docs] 1 
# [Source] ext - /home/gwern/.cache/R/fulltext 
# [IDs] 10.1371/journal.pone.0002019 ... 
R> library(pubchunks)
R> y <- (fulltext %>% ft_collect("author", "abstract", "title", "abstract") %>% pub_chunks())
R> y <- y$plos[[1]]
R> y
# <pub chunks>
#   from: xml_document
#   publisher/journal: plos/PLoS ONE
#   sections: all
#   showing up to first 5: 
#    front (n=2): nested list
#    body (n=23): The health benefits of regularly performed physica
#    back (n=2): nested list
#    title (n=1): Unique Environmental Effects on Physical Activity  ...
#    doi (n=1): 10.1371/journal.pone.0002019
R> y$body
# [1] "The health benefits of regularly performed physical activity are well established and include weight control, improved cardiorespiratory fitness, and decreased risk for chronic diseases such as cardiovascular disease, type 2 diabetes, and some forms of cancer [1]–[5]. Despite the recognized health benefits of an active lifestyle, the majority of the U.S. population, and that of many other industrialized nations, does not engage in physical activity levels consistent with recommendations for achieving health benefits [6]–[9]. Thus, identifying the barriers to and facilitators of regular participation in physical activity is critical for health promotion."
# ...
R> y$abstract
[1] "BackgroundThe health benefits of regular physical activity are well established. However, the relative contribution 
     of heritable and environmental factors to physical activity participation remains controversial. Using a cut-point of 
    60 minutes of total activity per week, data from the GenomEUtwin project revealed consistent genetic influence on 
    physical activity participation in 37,051 twin pairs from seven countries. We hypothesized that the heritability of 
    physical activity participation would be attenuated using the CDC/ACSM recommended minimum threshold of 150 
    minutes of moderate intensity activity per week.MethodsData were obtained from 1,389 twin pairs from the 
    community-based University of Washington Twin Registry. Twin similarity in physical activity participation using 
    both cut-points was analyzed using tetrachoric correlations and structural equation modeling in all same-sex 
    pairs.ResultsCorrelations were higher in monozygotic (rMZ = 0.43, 95% CI = 0.33–0.54) than dizygotic pairs 
    (rDZ = 0.30, 95% CI = 0.12–0.47) using the 60 minute cut-point. However, differences were attenuated using the 
    150 minute standard (rMZ = 0.30, 95% CI = 0.20–0.40; rDZ = 0.25, 95% CI = 0.07–0.42). Using the lower cut-point,
    the best fitting model of twin resemblance only included additive genetics and unique environment, with a heritability 
    of 45%. In contrast, using the higher threshold, the best fitting model included the common and unique environment, 
    with the unique environment contributing 72% of the variance.ConclusionUnique environment factors provide the 
    strongest influence on physical activity participation at levels recommended for health benefits."
~~~

It seems all of the formatting is simply dropped silently, so "**Background** The health benefits" becomes "BackgroundThe health benefits". I looked at the docs but couldn't find any options or alternative functions which said it would avoid this mangling. This isn't so bad for the subscripts because they're unique enough I could add another regexp/string substitution to fix them back up, but stuff like "MethodsData" or "ConclusionsUnique" I would have a hard time ensuring that the regexp was safe, especially as there are so many different internal names for abstract topics.

It would be better for this to be handled sensibly upstream. At least in the ones I've looked out, the inline formatting seems pretty much to be HTML and it would work for me if `pubchunks` simply avoided deleting them, either by default or as an option I can enable.

**Comment by sckott** [comment]
thanks, having a look

**Comment by sckott** [comment]
work on a new branch. install `remotes::install_github("ropensci/pubchunks@extract-param")` to try. See new param `extract` in `pub_chunks()`, set `extract="as.character` which will be used instead of `xml2::xml_text` whenever we've retrieved the section of text from an article and are ready to convert to a string. turns out as.character will preserve any tags whereas xml_text strips them

**Comment by gwern** [comment]
Works for me. Had to rewrite my code a little to treat the abstract separately (I don't want the XML in the authors/title), but otherwise that option works, thanks.

**Comment by sckott** [comment]
Great, glad it works. 

will try to get a new version to cran soon
